-- Жанр (пополняемый словарь)
DROP TABLE IF EXISTS genre CASCADE;
CREATE TABLE genre (
    uid SERIAL PRIMARY KEY,
    name varchar(50)  NOT NULL, 
    code varchar(50)  CONSTRAINT genrecode_must_be_different UNIQUE NOT NULL 
    );
    
-- Инициализируем таблицу жанров
INSERT INTO genre (code, name) VALUES 
                ('sf_history', 'Альтернативнаяистория'),
                ('sf_action', 'БоеваяФантастика'),
                ('sf_epic', 'ЭпическаяФантастика'),
                ('sf_heroic', 'Героическаяфантастика'),
                ('sf_detective', 'ДетективнаяФантастика'),
                ('sf_cyberpunk', 'Киберпанк'),
                ('sf_space', 'КосмическаяФантастика'),
                ('sf_social', 'Социальнаяфантастика'),
                ('sf_horror', 'УжасыиМистика'),
                ('sf_humor', 'Юмористическаяфантастика'),
                ('sf_fantasy', 'Фэнтези'),
                ('sf', 'НаучнаяФантастика'),
                ('det_classic', 'КлассическийДетектив'),
                ('det_police', 'ПолицейскийДетектив'),
                ('det_action', 'Боевики'),
                ('det_irony', 'ИроническийДетектив'),
                ('det_history', 'ИсторическийДетектив'),
                ('det_espionage', 'ШпионскийДетектив'),
                ('det_crime', 'КриминальныйДетектив'),
                ('det_political', 'ПолитическийДетектив'),
                ('det_maniac', 'Маньяки'),
                ('det_hard', 'КрутойДетектив'),
                ('thriller', 'Триллеры'),
                ('detective', 'Детектив'),
                ('love_detective', 'ОстросюжетныеЛюбовныеРоманы'),
                ('prose', 'Проза'),
                ('prose_classic', 'КлассическаяПроза'),
                ('prose_history', 'ИсторическаяПроза'),
                ('prose_contemporary', 'СовременнаяПроза'),
                ('prose_counter', 'Контркультура'),
                ('prose_rus_classic', 'РусскаяКлассика'),
                ('prose_su_classics', 'СоветскаяКлассика'),
                ('child_prose', 'ДетскаяПроза'),
                ('love', 'Любовныероманы'),
                ('love_contemporary', 'СовременныеЛюбовныеРоманы'),
                ('love_history', 'ИсторическиеЛюбовныеРоманы'),
                ('love_short', 'КороткиеЛюбовныеРоманы'),
                ('love_erotica', 'Эротика'),
                ('adv_western', 'Вестерны'),
                ('adv_history', 'ИсторическиеПриключения'),
                ('adv_indian', 'Приключения:Индейцы'),
                ('adv_maritime', 'МорскиеПриключения'),
                ('adv_geo', 'ПутешествияиГеография'),
                ('adventure', 'Приключения:Прочее'),
                ('children', 'Детское'),
                ('child_tale', 'Сказки'),
                ('child_verse', 'ДетскиеСтихи'),
                ('child_sf', 'ДетскаяФантастика'),
                ('child_det', 'ДетскиеОстросюжетные'),
                ('child_adv', 'ДетскиеПриключения'),
                ('child_education', 'ДетскаяОбразовательнаялитература'),
                ('poetry', 'Поэзия'),
                ('dramaturgy', 'Драматургия'),
                ('humor_verse', 'ЮмористическиеСтихи'),
                ('antique_ant', 'АнтичнаяЛитература'),
                ('antique_european', 'ЕвропейскаяСтариннаяЛитература'),
                ('antique_russian', 'ДревнерусскаяЛитература'),
                ('antique_east', 'ДревневосточнаяЛитература'),
                ('antique_myths', 'Мифы.Легенды.Эпос'),
                ('antique', 'СтариннаяЛитература:Прочее'),
                ('sci_history', 'История'),
                ('sci_psychology', 'Психология'),
                ('sci_culture', 'Культурология'),
                ('sci_religion', 'Религиоведение'),
                ('sci_philosophy', 'Философия'),
                ('sci_politics', 'Политика'),
                ('sci_business', 'Деловаялитература'),
                ('sci_juris', 'Юриспруденция'),
                ('sci_linguistic', 'Языкознание'),
                ('sci_medicine', 'Медицина'),
                ('sci_phys', 'Физика'),
                ('sci_math', 'Математика'),
                ('sci_chem', 'Химия'),
                ('sci_biology', 'Биология'),
                ('sci_tech', 'Технические'),
                ('science', 'Научно-образовательная:Прочее'),
                ('comp_www', 'Интернет'),
                ('comp_programming', 'Программирование'),
                ('comp_hard', 'КомпьютерноеЖелезо'),
                ('comp_soft', 'Программы'),
                ('comp_db', 'БазыДанных'),
                ('comp_osnet', 'ОСиСети'),
                ('computers', 'Компьютеры:Прочее'),
                ('ref_encyc', 'Энциклопедии'),
                ('ref_dict', 'Словари'),
                ('ref_ref', 'Справочники'),
                ('ref_guide', 'Руководства'),
                ('reference', 'СправочнаяЛитература:Прочее'),
                ('nonf_biography', 'БиографиииМемуары'),
                ('nonf_publicism', 'Публицистика'),
                ('nonf_criticism', 'Критика'),
                ('nonfiction', 'Документальное:Прочее'),
                ('design', 'Искусство,Дизайн'),
                ('adv_animal', 'ПриродаиЖивотные'),
                ('religion', 'Религия'),
                ('religion_rel', 'Религия'),
                ('religion_esoterics', 'Эзотерика'),
                ('religion_self', 'Самосовершенствование'),
                ('humor_anecdote', 'Анекдоты'),
                ('humor_prose', 'ЮмористическаяПроза'),
                ('humor', 'Юмор:Прочее'),
                ('home_cooking', 'Кулинария'),
                ('home_pets', 'ДомашниеЖивотные'),
                ('home_crafts', 'Хобби,Ремесла'),
                ('home_entertain', 'Развлечения'),
                ('home_health', 'Здоровье'),
                ('home_garden', 'СадиОгород'),
                ('home_diy', 'СделайСам'),
                ('home_sport', 'Спорт'),
                ('home_sex', 'Эротика,Секс'),
                ('home', 'ДомиСемья:Прочее'),
                ('russian_contemporary', 'Российское современное'),
                ('foreign_contemporary', 'Зарубежное современное'),
                ('foreign_publicism', 'Современный публицизм'),
                ('proce','Проза');
                