CREATE USER kosfb2 PASSWORD 'AsDfGh123456';
ALTER USER kosfb2 SUPERUSER;

CREATE ROLE kosfb2 LOGIN ENCRYPTED PASSWORD 'AsDfGh123456';
ALTER ROLE kosfb2 SUPERUSER;

CREATE DATABASE fb2data;
GRANT ALL PRIVILEGES ON DATABASE fb2data to kosfb2;
\c fb2data
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO kosfb2;
